package com.lawencon.community.service;

import javax.mail.MessagingException;
import javax.mail.internet.MimeMessage;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.stereotype.Service;


@Service
public class EmailSenderService {

	@Autowired
	private JavaMailSender mailSender;


<<<<<<< HEAD
	public void sendEmail(String toEmail, String subject, String body) {
		final SimpleMailMessage message = new SimpleMailMessage();
		message.setFrom("ariprayoga007@gmail.com");
		message.setTo(toEmail);
		message.setSubject(subject);
		message.setText(body);

=======
	public void sendEmail(final String to, final String codeVerification) throws MessagingException {
		MimeMessage message = mailSender.createMimeMessage();
		message.setFrom("zelkiaanisa@gmail.com");
		message.setRecipients(MimeMessage.RecipientType.TO, to);
		message.setSubject("Code Verification Request");
		
		final String htmlContent = "<!DOCTYPE HTML\r\n"
				+ "  PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional //EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
				+ "<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\" style=\"line-height: inherit;\">\r\n"
				+ "\r\n"
				+ "<head>\r\n"
				+ "  <!--[if gte mso 9]>\r\n"
				+ "<xml>\r\n"
				+ "  <o:OfficeDocumentSettings>\r\n"
				+ "    <o:AllowPNG/>\r\n"
				+ "    <o:PixelsPerInch>96</o:PixelsPerInch>\r\n"
				+ "  </o:OfficeDocumentSettings>\r\n"
				+ "</xml>\r\n"
				+ "<![endif]-->\r\n"
				+ "  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n"
				+ "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
				+ "  <meta name=\"x-apple-disable-message-reformatting\">\r\n"
				+ "  <!--[if !mso]><!-->\r\n"
				+ "  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n"
				+ "  <!--<![endif]-->\r\n"
				+ "  <title></title>\r\n"
				+ "\r\n"
				+ "  <style type=\"text/css\">\r\n"
				+ "@media only screen and (min-width: 620px) {\r\n"
				+ "  .u-row {\r\n"
				+ "    width: 600px !important;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  .u-row .u-col {\r\n"
				+ "    vertical-align: top;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  .u-row .u-col-33p33 {\r\n"
				+ "    width: 199.98px !important;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  .u-row .u-col-100 {\r\n"
				+ "    width: 600px !important;\r\n"
				+ "  }\r\n"
				+ "}\r\n"
				+ "@media (max-width: 620px) {\r\n"
				+ "  .u-row-container {\r\n"
				+ "    max-width: 100% !important;\r\n"
				+ "    padding-left: 0px !important;\r\n"
				+ "    padding-right: 0px !important;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  .u-row .u-col {\r\n"
				+ "    min-width: 320px !important;\r\n"
				+ "    max-width: 100% !important;\r\n"
				+ "    display: block !important;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  .u-row {\r\n"
				+ "    width: 100% !important;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  .u-col {\r\n"
				+ "    width: 100% !important;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  .u-col>div {\r\n"
				+ "    margin: 0 auto;\r\n"
				+ "  }\r\n"
				+ "}\r\n"
				+ "@media (max-width: 480px) {\r\n"
				+ "  #u_content_text_4 .v-text-align {\r\n"
				+ "    text-align: center !important;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  #u_content_image_10 .v-src-width {\r\n"
				+ "    width: 100% !important;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  #u_content_image_10 .v-src-max-width {\r\n"
				+ "    max-width: 100% !important;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  #u_content_text_30 .v-text-align {\r\n"
				+ "    text-align: center !important;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  #u_content_text_33 .v-text-align {\r\n"
				+ "    text-align: center !important;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  #u_content_text_31 .v-text-align {\r\n"
				+ "    text-align: center !important;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  #u_content_text_34 .v-text-align {\r\n"
				+ "    text-align: center !important;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  #u_content_text_29 .v-text-align {\r\n"
				+ "    text-align: center !important;\r\n"
				+ "  }\r\n"
				+ "\r\n"
				+ "  #u_content_text_32 .v-text-align {\r\n"
				+ "    text-align: center !important;\r\n"
				+ "  }\r\n"
				+ "}\r\n"
				+ "</style>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "  <!--[if !mso]><!-->\r\n"
				+ "  <link href=\"https://fonts.googleapis.com/css?family=Cabin:400,700&display=swap\" rel=\"stylesheet\" type=\"text/css\">\r\n"
				+ "  <!--<![endif]-->\r\n"
				+ "\r\n"
				+ "</head>\r\n"
				+ "\r\n"
				+ "<body class=\"clean-body u_body\" style=\"line-height: inherit; margin: 0; padding: 0; -webkit-text-size-adjust: 100%; background-color: #ffffff; color: #000000;\">\r\n"
				+ "  <!--[if IE]><div class=\"ie-container\"><![endif]-->\r\n"
				+ "  <!--[if mso]><div class=\"mso-container\"><![endif]-->\r\n"
				+ "  <table id=\"u_body\" style=\"line-height: inherit; color: #000000; border-collapse: collapse; table-layout: fixed; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; vertical-align: top; min-width: 320px; Margin: 0 auto; background-color: #ffffff; width: 100%;\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" valign=\"top\" bgcolor=\"#ffffff\">\r\n"
				+ "    <tbody style=\"line-height: inherit;\">\r\n"
				+ "      <tr style=\"line-height: inherit; border-collapse: collapse; vertical-align: top;\" valign=\"top\">\r\n"
				+ "        <td style=\"line-height: inherit; color: #000000; word-break: break-word; vertical-align: top; border-collapse: collapse;\" valign=\"top\">\r\n"
				+ "          <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td align=\"center\" style=\"background-color: #ffffff;\"><![endif]-->\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "          <div class=\"u-row-container\" style=\"line-height: inherit; padding: 0px; background-color: transparent;\">\r\n"
				+ "            <div class=\"u-row\" style=\"line-height: inherit; Margin: 0 auto; min-width: 320px; max-width: 600px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; background-color: transparent;\">\r\n"
				+ "              <div style=\"line-height: inherit; border-collapse: collapse; display: table; width: 100%; height: 100%; background-color: transparent;\">\r\n"
				+ "                <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: transparent;\"><![endif]-->\r\n"
				+ "\r\n"
				+ "                <!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
				+ "                <div class=\"u-col u-col-100\" style=\"line-height: inherit; max-width: 320px; min-width: 600px; display: table-cell; vertical-align: top;\">\r\n"
				+ "                  <div style=\"line-height: inherit; height: 100%; width: 100%;\">\r\n"
				+ "                    <!--[if (!mso)&(!IE)]><!-->\r\n"
				+ "                    <div style=\"line-height: inherit; box-sizing: border-box; height: 100%; padding: 0px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-right: 0px solid transparent; border-bottom: 0px solid transparent;\">\r\n"
				+ "                      <!--<![endif]-->\r\n"
				+ "\r\n"
				+ "                      <table style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; font-family: arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\" valign=\"top\">\r\n"
				+ "                        <tbody style=\"line-height: inherit;\">\r\n"
				+ "                          <tr style=\"line-height: inherit; vertical-align: top; border-collapse: collapse;\" valign=\"top\">\r\n"
				+ "                            <td style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; overflow-wrap: break-word; word-break: break-word; padding: 21px 10px 20px; font-family: arial,helvetica,sans-serif;\" align=\"left\" valign=\"top\">\r\n"
				+ "\r\n"
				+ "                              <table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000;\" valign=\"top\">\r\n"
				+ "                                <tr style=\"line-height: inherit; vertical-align: top; border-collapse: collapse;\" valign=\"top\">\r\n"
				+ "                                  <td class=\"v-text-align\" style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; padding-right: 0px; padding-left: 0px;\" align=\"center\" valign=\"top\">\r\n"
				+ "\r\n"
				+ "                                    <img align=\"center\" border=\"0\" src=\"https://i.ibb.co/60KtbKQ/image-6.png\" alt=\"Image\" title=\"Image\" style=\"line-height: inherit; outline: none; text-decoration: none; -ms-interpolation-mode: bicubic; clear: both; border: none; height: auto; float: none; width: 29%; max-width: 168.2px; display: inline-block;\" width=\"168.2\" class=\"v-src-width v-src-max-width\">\r\n"
				+ "\r\n"
				+ "                                  </td>\r\n"
				+ "                                </tr>\r\n"
				+ "                              </table>\r\n"
				+ "\r\n"
				+ "                            </td>\r\n"
				+ "                          </tr>\r\n"
				+ "                        </tbody>\r\n"
				+ "                      </table>\r\n"
				+ "\r\n"
				+ "                      <!--[if (!mso)&(!IE)]><!-->\r\n"
				+ "                    </div>\r\n"
				+ "                    <!--<![endif]-->\r\n"
				+ "                  </div>\r\n"
				+ "                </div>\r\n"
				+ "                <!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "                <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
				+ "              </div>\r\n"
				+ "            </div>\r\n"
				+ "          </div>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "          <div class=\"u-row-container\" style=\"line-height: inherit; padding: 0px; background-color: transparent;\">\r\n"
				+ "            <div class=\"u-row\" style=\"line-height: inherit; Margin: 0 auto; min-width: 320px; max-width: 600px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; background-color: #7e8c8d;\">\r\n"
				+ "              <div style=\"line-height: inherit; border-collapse: collapse; display: table; width: 100%; height: 100%; background-image: url('https://i.ibb.co/NWyQsz1/image-5.png'); background-repeat: no-repeat; background-position: center top; background-color: transparent;\">\r\n"
				+ "                <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-image: url('https://i.ibb.co/NWyQsz1/image-5.png');background-repeat: no-repeat;background-position: center top;background-color: #7e8c8d;\"><![endif]-->\r\n"
				+ "\r\n"
				+ "                <!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
				+ "                <div class=\"u-col u-col-100\" style=\"line-height: inherit; max-width: 320px; min-width: 600px; display: table-cell; vertical-align: top;\">\r\n"
				+ "                  <div style=\"line-height: inherit; height: 100%; width: 100%;\">\r\n"
				+ "                    <!--[if (!mso)&(!IE)]><!-->\r\n"
				+ "                    <div style=\"line-height: inherit; box-sizing: border-box; height: 100%; padding: 0px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-right: 0px solid transparent; border-bottom: 0px solid transparent;\">\r\n"
				+ "                      <!--<![endif]-->\r\n"
				+ "\r\n"
				+ "                      <table id=\"u_content_text_4\" style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; font-family: arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\" valign=\"top\">\r\n"
				+ "                        <tbody style=\"line-height: inherit;\">\r\n"
				+ "                          <tr style=\"line-height: inherit; vertical-align: top; border-collapse: collapse;\" valign=\"top\">\r\n"
				+ "                            <td style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; overflow-wrap: break-word; word-break: break-word; padding: 23px 10px 10px; font-family: arial,helvetica,sans-serif;\" align=\"left\" valign=\"top\">\r\n"
				+ "\r\n"
				+ "                              <div class=\"v-text-align\" style=\"color: #ffffff; line-height: 150%; text-align: center; word-wrap: break-word;\">\r\n"
				+ "                                <p style=\"margin: 0; font-size: 14px; line-height: 150%;\"><span style=\"font-family: Cabin, sans-serif; font-size: 14px; line-height: 21px;\"><span style=\"font-size: 28px; line-height: 42px;\"><span style=\"line-height: 42px; font-size: 28px;\">We're happy </span></span></span>\r\n"
				+ "                                </p>\r\n"
				+ "                                <p style=\"margin: 0; font-size: 14px; line-height: 150%;\"><span style=\"font-family: Cabin, sans-serif; font-size: 14px; line-height: 21px;\"><span style=\"font-size: 28px; line-height: 42px;\"><span style=\"line-height: 42px; font-size: 28px;\">you're here.</span></span></span>\r\n"
				+ "                                </p>\r\n"
				+ "                              </div>\r\n"
				+ "\r\n"
				+ "                            </td>\r\n"
				+ "                          </tr>\r\n"
				+ "                        </tbody>\r\n"
				+ "                      </table>\r\n"
				+ "\r\n"
				+ "                      <table style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; font-family: arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\" valign=\"top\">\r\n"
				+ "                        <tbody style=\"line-height: inherit;\">\r\n"
				+ "                          <tr style=\"line-height: inherit; vertical-align: top; border-collapse: collapse;\" valign=\"top\">\r\n"
				+ "                            <td style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; overflow-wrap: break-word; word-break: break-word; padding: 0px 10px 10px; font-family: arial,helvetica,sans-serif;\" align=\"left\" valign=\"top\">\r\n"
				+ "\r\n"
				+ "                              <div class=\"v-text-align\" style=\"color: #ffffff; line-height: 160%; text-align: center; word-wrap: break-word;\">\r\n"
				+ "                                <p style=\"margin: 0; font-size: 14px; line-height: 160%;\">Congratulation for register new account\r\n"
				+ "                                </p>\r\n"
				+ "                              </div>\r\n"
				+ "\r\n"
				+ "                            </td>\r\n"
				+ "                          </tr>\r\n"
				+ "                        </tbody>\r\n"
				+ "                      </table>\r\n"
				+ "\r\n"
				+ "                      <!--[if (!mso)&(!IE)]><!-->\r\n"
				+ "                    </div>\r\n"
				+ "                    <!--<![endif]-->\r\n"
				+ "                  </div>\r\n"
				+ "                </div>\r\n"
				+ "                <!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "                <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
				+ "              </div>\r\n"
				+ "            </div>\r\n"
				+ "          </div>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "          <div class=\"u-row-container\" style=\"line-height: inherit; padding: 0px; background-color: transparent;\">\r\n"
				+ "            <div class=\"u-row\" style=\"line-height: inherit; Margin: 0 auto; min-width: 320px; max-width: 600px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; background-color: #e4faf4;\">\r\n"
				+ "              <div style=\"line-height: inherit; border-collapse: collapse; display: table; width: 100%; height: 100%; background-color: transparent;\">\r\n"
				+ "                <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #e4faf4;\"><![endif]-->\r\n"
				+ "\r\n"
				+ "                <!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
				+ "                <div class=\"u-col u-col-100\" style=\"line-height: inherit; max-width: 320px; min-width: 600px; display: table-cell; vertical-align: top;\">\r\n"
				+ "                  <div style=\"line-height: inherit; height: 100%; width: 100%;\">\r\n"
				+ "                    <!--[if (!mso)&(!IE)]><!-->\r\n"
				+ "                    <div style=\"line-height: inherit; box-sizing: border-box; height: 100%; padding: 0px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-right: 0px solid transparent; border-bottom: 0px solid transparent;\">\r\n"
				+ "                      <!--<![endif]-->\r\n"
				+ "\r\n"
				+ "                      <table style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; font-family: arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\" valign=\"top\">\r\n"
				+ "                        <tbody style=\"line-height: inherit;\">\r\n"
				+ "                          <tr style=\"line-height: inherit; vertical-align: top; border-collapse: collapse;\" valign=\"top\">\r\n"
				+ "                            <td style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; overflow-wrap: break-word; word-break: break-word; padding: 45px 10px 10px; font-family: arial,helvetica,sans-serif;\" align=\"left\" valign=\"top\">\r\n"
				+ "\r\n"
				+ "                              <div class=\"v-text-align\" style=\"line-height: 140%; text-align: center; word-wrap: break-word;\">\r\n"
				+ "                                <p style=\"margin: 0; font-size: 14px; line-height: 140%;\"><span style=\"font-family: Cabin, sans-serif; font-size: 20px; line-height: 28px;\">Trusted\r\n"
				+ "                                    by Millions of People</span></p>\r\n"
				+ "                              </div>\r\n"
				+ "\r\n"
				+ "                            </td>\r\n"
				+ "                          </tr>\r\n"
				+ "                        </tbody>\r\n"
				+ "                      </table>\r\n"
				+ "\r\n"
				+ "                      <table style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; font-family: arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\" valign=\"top\">\r\n"
				+ "                        <tbody style=\"line-height: inherit;\">\r\n"
				+ "                          <tr style=\"line-height: inherit; vertical-align: top; border-collapse: collapse;\" valign=\"top\">\r\n"
				+ "                            <td style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; overflow-wrap: break-word; word-break: break-word; padding: 0px 10px 10px; font-family: arial,helvetica,sans-serif;\" align=\"left\" valign=\"top\">\r\n"
				+ "\r\n"
				+ "                              <div class=\"v-text-align\" style=\"color: #4c5763; line-height: 180%; text-align: center; word-wrap: break-word;\">\r\n"
				+ "                                <p style=\"margin: 0; font-size: 14px; line-height: 180%;\">WeCommunity help connect people and share\r\n"
				+ "                                  knowledge. If you didn't create an account with WeCommunity, you can safely delete\r\n"
				+ "                                  this email.</p>\r\n"
				+ "                              </div>\r\n"
				+ "\r\n"
				+ "                            </td>\r\n"
				+ "                          </tr>\r\n"
				+ "                        </tbody>\r\n"
				+ "                      </table>\r\n"
				+ "\r\n"
				+ "                      <table style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; font-family: arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\" valign=\"top\">\r\n"
				+ "                        <tbody style=\"line-height: inherit;\">\r\n"
				+ "                          <tr style=\"line-height: inherit; vertical-align: top; border-collapse: collapse;\" valign=\"top\">\r\n"
				+ "                            <td style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; overflow-wrap: break-word; word-break: break-word; padding: 0px 10px 10px; font-family: arial,helvetica,sans-serif;\" align=\"left\" valign=\"top\">\r\n"
				+ "\r\n"
				+ "                              <div class=\"v-text-align\" style=\"color: #4c5763; line-height: 180%; text-align: center; word-wrap: break-word;\">\r\n"
				+ "                                <p style=\"margin: 0; line-height: 180%;\"><span style=\"font-size: 22px; line-height: 39.6px; color: #236fa1; background-color: #c2e0f4;\">"
				+ codeVerification
				+ "</span>\r\n"
				+ "                                </p>\r\n"
				+ "                              </div>\r\n"
				+ "\r\n"
				+ "                            </td>\r\n"
				+ "                          </tr>\r\n"
				+ "                        </tbody>\r\n"
				+ "                      </table>\r\n"
				+ "\r\n"
				+ "                      <table style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; font-family: arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\" valign=\"top\">\r\n"
				+ "                        <tbody style=\"line-height: inherit;\">\r\n"
				+ "                          <tr style=\"line-height: inherit; vertical-align: top; border-collapse: collapse;\" valign=\"top\">\r\n"
				+ "                            <td style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; overflow-wrap: break-word; word-break: break-word; padding: 0px 10px 10px; font-family: arial,helvetica,sans-serif;\" align=\"left\" valign=\"top\">\r\n"
				+ "\r\n"
				+ "                              <div class=\"v-text-align\" style=\"color: #4c5763; line-height: 180%; text-align: center; word-wrap: break-word;\">\r\n"
				+ "                                <p style=\"margin: 0; font-size: 14px; line-height: 180%;\">You can <strong style=\"line-height: inherit;\">copy </strong>your\r\n"
				+ "                                  verification code above and paste to WeCommunity web.</p>\r\n"
				+ "                              </div>\r\n"
				+ "\r\n"
				+ "                            </td>\r\n"
				+ "                          </tr>\r\n"
				+ "                        </tbody>\r\n"
				+ "                      </table>\r\n"
				+ "\r\n"
				+ "                      <!--[if (!mso)&(!IE)]><!-->\r\n"
				+ "                    </div>\r\n"
				+ "                    <!--<![endif]-->\r\n"
				+ "                  </div>\r\n"
				+ "                </div>\r\n"
				+ "                <!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "                <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
				+ "              </div>\r\n"
				+ "            </div>\r\n"
				+ "          </div>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "          <div class=\"u-row-container\" style=\"line-height: inherit; padding: 0px; background-color: transparent;\">\r\n"
				+ "            <div class=\"u-row\" style=\"line-height: inherit; Margin: 0 auto; min-width: 320px; max-width: 600px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; background-color: transparent;\">\r\n"
				+ "              <div style=\"line-height: inherit; border-collapse: collapse; display: table; width: 100%; height: 100%; background-color: transparent;\">\r\n"
				+ "                <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: transparent;\"><![endif]-->\r\n"
				+ "\r\n"
				+ "                <!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
				+ "                <div class=\"u-col u-col-100\" style=\"line-height: inherit; max-width: 320px; min-width: 600px; display: table-cell; vertical-align: top;\">\r\n"
				+ "                  <div style=\"line-height: inherit; height: 100%; width: 100%;\">\r\n"
				+ "                    <!--[if (!mso)&(!IE)]><!-->\r\n"
				+ "                    <div style=\"line-height: inherit; box-sizing: border-box; height: 100%; padding: 0px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-right: 0px solid transparent; border-bottom: 0px solid transparent;\">\r\n"
				+ "                      <!--<![endif]-->\r\n"
				+ "\r\n"
				+ "                      <table style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; font-family: arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\" valign=\"top\">\r\n"
				+ "                        <tbody style=\"line-height: inherit;\">\r\n"
				+ "                          <tr style=\"line-height: inherit; vertical-align: top; border-collapse: collapse;\" valign=\"top\">\r\n"
				+ "                            <td style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; overflow-wrap: break-word; word-break: break-word; padding: 20px; font-family: arial,helvetica,sans-serif;\" align=\"left\" valign=\"top\">\r\n"
				+ "\r\n"
				+ "                              <table height=\"0px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"line-height: inherit; color: #000000; border-collapse: collapse; table-layout: fixed; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; vertical-align: top; border-top: 0px solid #BBBBBB; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\" valign=\"top\">\r\n"
				+ "                                <tbody style=\"line-height: inherit;\">\r\n"
				+ "                                  <tr style=\"line-height: inherit; border-collapse: collapse; vertical-align: top;\" valign=\"top\">\r\n"
				+ "                                    <td style=\"color: #000000; word-break: break-word; vertical-align: top; font-size: 0px; line-height: 0px; mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; border-collapse: collapse;\" valign=\"top\">\r\n"
				+ "                                      <span style=\"line-height: inherit;\">&#160;</span>\r\n"
				+ "                                    </td>\r\n"
				+ "                                  </tr>\r\n"
				+ "                                </tbody>\r\n"
				+ "                              </table>\r\n"
				+ "\r\n"
				+ "                            </td>\r\n"
				+ "                          </tr>\r\n"
				+ "                        </tbody>\r\n"
				+ "                      </table>\r\n"
				+ "\r\n"
				+ "                      <!--[if (!mso)&(!IE)]><!-->\r\n"
				+ "                    </div>\r\n"
				+ "                    <!--<![endif]-->\r\n"
				+ "                  </div>\r\n"
				+ "                </div>\r\n"
				+ "                <!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "                <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
				+ "              </div>\r\n"
				+ "            </div>\r\n"
				+ "          </div>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "          <div class=\"u-row-container\" style=\"line-height: inherit; padding: 0px; background-color: transparent;\">\r\n"
				+ "            <div class=\"u-row\" style=\"line-height: inherit; Margin: 0 auto; min-width: 320px; max-width: 600px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; background-color: transparent;\">\r\n"
				+ "              <div style=\"line-height: inherit; border-collapse: collapse; display: table; width: 100%; height: 100%; background-color: transparent;\">\r\n"
				+ "                <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: transparent;\"><![endif]-->\r\n"
				+ "\r\n"
				+ "                <!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
				+ "                <div class=\"u-col u-col-100\" style=\"line-height: inherit; max-width: 320px; min-width: 600px; display: table-cell; vertical-align: top;\">\r\n"
				+ "                  <div style=\"line-height: inherit; height: 100%; width: 100%;\">\r\n"
				+ "                    <!--[if (!mso)&(!IE)]><!-->\r\n"
				+ "                    <div style=\"line-height: inherit; box-sizing: border-box; height: 100%; padding: 0px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-right: 0px solid transparent; border-bottom: 0px solid transparent;\">\r\n"
				+ "                      <!--<![endif]-->\r\n"
				+ "\r\n"
				+ "                      <table id=\"u_content_image_10\" style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; font-family: arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\" valign=\"top\">\r\n"
				+ "                        <tbody style=\"line-height: inherit;\">\r\n"
				+ "                          <tr style=\"line-height: inherit; vertical-align: top; border-collapse: collapse;\" valign=\"top\">\r\n"
				+ "                            <td style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; overflow-wrap: break-word; word-break: break-word; padding: 0px; font-family: arial,helvetica,sans-serif;\" align=\"left\" valign=\"top\">\r\n"
				+ "\r\n"
				+ "                              <table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000;\" valign=\"top\">\r\n"
				+ "                                <tr style=\"line-height: inherit; vertical-align: top; border-collapse: collapse;\" valign=\"top\">\r\n"
				+ "                                  <td class=\"v-text-align\" style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; padding-right: 0px; padding-left: 0px;\" align=\"center\" valign=\"top\">\r\n"
				+ "\r\n"
				+ "                                    <img align=\"center\" border=\"0\" src=\"https://i.ibb.co/0YNcHwK/image-4.png\" alt=\"Image\" title=\"Image\" style=\"line-height: inherit; outline: none; text-decoration: none; -ms-interpolation-mode: bicubic; clear: both; border: none; height: auto; float: none; width: 100%; max-width: 600px; display: inline-block;\" width=\"600\" class=\"v-src-width v-src-max-width\">\r\n"
				+ "\r\n"
				+ "                                  </td>\r\n"
				+ "                                </tr>\r\n"
				+ "                              </table>\r\n"
				+ "\r\n"
				+ "                            </td>\r\n"
				+ "                          </tr>\r\n"
				+ "                        </tbody>\r\n"
				+ "                      </table>\r\n"
				+ "\r\n"
				+ "                      <!--[if (!mso)&(!IE)]><!-->\r\n"
				+ "                    </div>\r\n"
				+ "                    <!--<![endif]-->\r\n"
				+ "                  </div>\r\n"
				+ "                </div>\r\n"
				+ "                <!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "                <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
				+ "              </div>\r\n"
				+ "            </div>\r\n"
				+ "          </div>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "          <div class=\"u-row-container\" style=\"line-height: inherit; padding: 0px; background-color: transparent;\">\r\n"
				+ "            <div class=\"u-row\" style=\"line-height: inherit; Margin: 0 auto; min-width: 320px; max-width: 600px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; background-color: #d9f7ed;\">\r\n"
				+ "              <div style=\"line-height: inherit; border-collapse: collapse; display: table; width: 100%; height: 100%; background-color: transparent;\">\r\n"
				+ "                <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #d9f7ed;\"><![endif]-->\r\n"
				+ "\r\n"
				+ "                <!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
				+ "                <div class=\"u-col u-col-100\" style=\"line-height: inherit; max-width: 320px; min-width: 600px; display: table-cell; vertical-align: top;\">\r\n"
				+ "                  <div style=\"line-height: inherit; height: 100%; width: 100%;\">\r\n"
				+ "                    <!--[if (!mso)&(!IE)]><!-->\r\n"
				+ "                    <div style=\"line-height: inherit; box-sizing: border-box; height: 100%; padding: 0px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-right: 0px solid transparent; border-bottom: 0px solid transparent;\">\r\n"
				+ "                      <!--<![endif]-->\r\n"
				+ "\r\n"
				+ "                      <table style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; font-family: arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\" valign=\"top\">\r\n"
				+ "                        <tbody style=\"line-height: inherit;\">\r\n"
				+ "                          <tr style=\"line-height: inherit; vertical-align: top; border-collapse: collapse;\" valign=\"top\">\r\n"
				+ "                            <td style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; overflow-wrap: break-word; word-break: break-word; padding: 10px; font-family: arial,helvetica,sans-serif;\" align=\"left\" valign=\"top\">\r\n"
				+ "\r\n"
				+ "                              <table height=\"0px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"line-height: inherit; color: #000000; border-collapse: collapse; table-layout: fixed; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; vertical-align: top; border-top: 0px solid #BBBBBB; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\" valign=\"top\">\r\n"
				+ "                                <tbody style=\"line-height: inherit;\">\r\n"
				+ "                                  <tr style=\"line-height: inherit; border-collapse: collapse; vertical-align: top;\" valign=\"top\">\r\n"
				+ "                                    <td style=\"color: #000000; word-break: break-word; vertical-align: top; font-size: 0px; line-height: 0px; mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; border-collapse: collapse;\" valign=\"top\">\r\n"
				+ "                                      <span style=\"line-height: inherit;\">&#160;</span>\r\n"
				+ "                                    </td>\r\n"
				+ "                                  </tr>\r\n"
				+ "                                </tbody>\r\n"
				+ "                              </table>\r\n"
				+ "\r\n"
				+ "                            </td>\r\n"
				+ "                          </tr>\r\n"
				+ "                        </tbody>\r\n"
				+ "                      </table>\r\n"
				+ "\r\n"
				+ "                      <!--[if (!mso)&(!IE)]><!-->\r\n"
				+ "                    </div>\r\n"
				+ "                    <!--<![endif]-->\r\n"
				+ "                  </div>\r\n"
				+ "                </div>\r\n"
				+ "                <!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "                <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
				+ "              </div>\r\n"
				+ "            </div>\r\n"
				+ "          </div>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "          <div class=\"u-row-container\" style=\"line-height: inherit; padding: 0px; background-color: transparent;\">\r\n"
				+ "            <div class=\"u-row\" style=\"line-height: inherit; Margin: 0 auto; min-width: 320px; max-width: 600px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; background-color: #d9f7ed;\">\r\n"
				+ "              <div style=\"line-height: inherit; border-collapse: collapse; display: table; width: 100%; height: 100%; background-color: transparent;\">\r\n"
				+ "                <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #d9f7ed;\"><![endif]-->\r\n"
				+ "\r\n"
				+ "                <!--[if (mso)|(IE)]><td align=\"center\" width=\"200\" style=\"width: 200px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
				+ "                <div class=\"u-col u-col-33p33\" style=\"line-height: inherit; max-width: 320px; min-width: 200px; display: table-cell; vertical-align: top;\">\r\n"
				+ "                  <div style=\"line-height: inherit; height: 100%; width: 100%;\">\r\n"
				+ "                    <!--[if (!mso)&(!IE)]><!-->\r\n"
				+ "                    <div style=\"line-height: inherit; box-sizing: border-box; height: 100%; padding: 0px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-right: 0px solid transparent; border-bottom: 0px solid transparent;\">\r\n"
				+ "                      <!--<![endif]-->\r\n"
				+ "\r\n"
				+ "                      <table id=\"u_content_text_30\" style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; font-family: arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\" valign=\"top\">\r\n"
				+ "                        <tbody style=\"line-height: inherit;\">\r\n"
				+ "                          <tr style=\"line-height: inherit; vertical-align: top; border-collapse: collapse;\" valign=\"top\">\r\n"
				+ "                            <td style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; overflow-wrap: break-word; word-break: break-word; padding: 10px; font-family: arial,helvetica,sans-serif;\" align=\"left\" valign=\"top\">\r\n"
				+ "\r\n"
				+ "                              <div class=\"v-text-align\" style=\"color: #00d09c; line-height: 140%; text-align: center; word-wrap: break-word;\">\r\n"
				+ "                                <p style=\"margin: 0; line-height: 140%;\">Address</p>\r\n"
				+ "                              </div>\r\n"
				+ "\r\n"
				+ "                            </td>\r\n"
				+ "                          </tr>\r\n"
				+ "                        </tbody>\r\n"
				+ "                      </table>\r\n"
				+ "\r\n"
				+ "                      <table id=\"u_content_text_33\" style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; font-family: arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\" valign=\"top\">\r\n"
				+ "                        <tbody style=\"line-height: inherit;\">\r\n"
				+ "                          <tr style=\"line-height: inherit; vertical-align: top; border-collapse: collapse;\" valign=\"top\">\r\n"
				+ "                            <td style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; overflow-wrap: break-word; word-break: break-word; padding: 10px; font-family: arial,helvetica,sans-serif;\" align=\"left\" valign=\"top\">\r\n"
				+ "\r\n"
				+ "                              <div class=\"v-text-align\" style=\"color: #4c5763; line-height: 170%; text-align: center; word-wrap: break-word;\">\r\n"
				+ "                                <p style=\"margin: 0; font-size: 14px; line-height: 170%;\"><span style=\"font-size: 14px; line-height: 23.8px;\">Jalan Raya Casablanca, Jakarta\r\n"
				+ "                                    Selatan</span></p>\r\n"
				+ "                              </div>\r\n"
				+ "\r\n"
				+ "                            </td>\r\n"
				+ "                          </tr>\r\n"
				+ "                        </tbody>\r\n"
				+ "                      </table>\r\n"
				+ "\r\n"
				+ "                      <!--[if (!mso)&(!IE)]><!-->\r\n"
				+ "                    </div>\r\n"
				+ "                    <!--<![endif]-->\r\n"
				+ "                  </div>\r\n"
				+ "                </div>\r\n"
				+ "                <!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "                <!--[if (mso)|(IE)]><td align=\"center\" width=\"200\" style=\"width: 200px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
				+ "                <div class=\"u-col u-col-33p33\" style=\"line-height: inherit; max-width: 320px; min-width: 200px; display: table-cell; vertical-align: top;\">\r\n"
				+ "                  <div style=\"line-height: inherit; height: 100%; width: 100%;\">\r\n"
				+ "                    <!--[if (!mso)&(!IE)]><!-->\r\n"
				+ "                    <div style=\"line-height: inherit; box-sizing: border-box; height: 100%; padding: 0px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-right: 0px solid transparent; border-bottom: 0px solid transparent;\">\r\n"
				+ "                      <!--<![endif]-->\r\n"
				+ "\r\n"
				+ "                      <table id=\"u_content_text_31\" style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; font-family: arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\" valign=\"top\">\r\n"
				+ "                        <tbody style=\"line-height: inherit;\">\r\n"
				+ "                          <tr style=\"line-height: inherit; vertical-align: top; border-collapse: collapse;\" valign=\"top\">\r\n"
				+ "                            <td style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; overflow-wrap: break-word; word-break: break-word; padding: 10px; font-family: arial,helvetica,sans-serif;\" align=\"left\" valign=\"top\">\r\n"
				+ "\r\n"
				+ "                              <div class=\"v-text-align\" style=\"color: #00d09c; line-height: 140%; text-align: center; word-wrap: break-word;\">\r\n"
				+ "                                <p style=\"margin: 0; font-size: 14px; line-height: 140%;\"><span style=\"font-family: Cabin, sans-serif; font-size: 14px; line-height: 19.6px;\"><span style=\"font-size: 16px; line-height: 22.4px;\">Contact Info</span><br style=\"line-height: inherit;\"></span></p>\r\n"
				+ "                              </div>\r\n"
				+ "\r\n"
				+ "                            </td>\r\n"
				+ "                          </tr>\r\n"
				+ "                        </tbody>\r\n"
				+ "                      </table>\r\n"
				+ "\r\n"
				+ "                      <table id=\"u_content_text_34\" style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; font-family: arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\" valign=\"top\">\r\n"
				+ "                        <tbody style=\"line-height: inherit;\">\r\n"
				+ "                          <tr style=\"line-height: inherit; vertical-align: top; border-collapse: collapse;\" valign=\"top\">\r\n"
				+ "                            <td style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; overflow-wrap: break-word; word-break: break-word; padding: 10px; font-family: arial,helvetica,sans-serif;\" align=\"left\" valign=\"top\">\r\n"
				+ "\r\n"
				+ "                              <div class=\"v-text-align\" style=\"color: #4c5763; line-height: 170%; text-align: center; word-wrap: break-word;\">\r\n"
				+ "                                <p style=\"margin: 0; font-size: 14px; line-height: 170%;\">+62 189 123</p>\r\n"
				+ "                                <p style=\"margin: 0; font-size: 14px; line-height: 170%;\">support@wecommunity.com <br style=\"line-height: inherit;\"><br style=\"line-height: inherit;\"></p>\r\n"
				+ "                              </div>\r\n"
				+ "\r\n"
				+ "                            </td>\r\n"
				+ "                          </tr>\r\n"
				+ "                        </tbody>\r\n"
				+ "                      </table>\r\n"
				+ "\r\n"
				+ "                      <!--[if (!mso)&(!IE)]><!-->\r\n"
				+ "                    </div>\r\n"
				+ "                    <!--<![endif]-->\r\n"
				+ "                  </div>\r\n"
				+ "                </div>\r\n"
				+ "                <!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "                <!--[if (mso)|(IE)]><td align=\"center\" width=\"200\" style=\"width: 200px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
				+ "                <div class=\"u-col u-col-33p33\" style=\"line-height: inherit; max-width: 320px; min-width: 200px; display: table-cell; vertical-align: top;\">\r\n"
				+ "                  <div style=\"line-height: inherit; height: 100%; width: 100%;\">\r\n"
				+ "                    <!--[if (!mso)&(!IE)]><!-->\r\n"
				+ "                    <div style=\"line-height: inherit; box-sizing: border-box; height: 100%; padding: 0px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-right: 0px solid transparent; border-bottom: 0px solid transparent;\">\r\n"
				+ "                      <!--<![endif]-->\r\n"
				+ "\r\n"
				+ "                      <table id=\"u_content_text_29\" style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; font-family: arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\" valign=\"top\">\r\n"
				+ "                        <tbody style=\"line-height: inherit;\">\r\n"
				+ "                          <tr style=\"line-height: inherit; vertical-align: top; border-collapse: collapse;\" valign=\"top\">\r\n"
				+ "                            <td style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; overflow-wrap: break-word; word-break: break-word; padding: 10px; font-family: arial,helvetica,sans-serif;\" align=\"left\" valign=\"top\">\r\n"
				+ "\r\n"
				+ "                              <div class=\"v-text-align\" style=\"color: #00d09c; line-height: 140%; text-align: center; word-wrap: break-word;\">\r\n"
				+ "                                <p style=\"margin: 0; font-size: 14px; line-height: 140%;\"><span style=\"font-family: Cabin, sans-serif; font-size: 16px; line-height: 22.4px;\">WeCommunity<br style=\"line-height: inherit;\"></span>\r\n"
				+ "                                </p>\r\n"
				+ "                              </div>\r\n"
				+ "\r\n"
				+ "                            </td>\r\n"
				+ "                          </tr>\r\n"
				+ "                        </tbody>\r\n"
				+ "                      </table>\r\n"
				+ "\r\n"
				+ "                      <table id=\"u_content_text_32\" style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; font-family: arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\" valign=\"top\">\r\n"
				+ "                        <tbody style=\"line-height: inherit;\">\r\n"
				+ "                          <tr style=\"line-height: inherit; vertical-align: top; border-collapse: collapse;\" valign=\"top\">\r\n"
				+ "                            <td style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; overflow-wrap: break-word; word-break: break-word; padding: 10px; font-family: arial,helvetica,sans-serif;\" align=\"left\" valign=\"top\">\r\n"
				+ "\r\n"
				+ "                              <div class=\"v-text-align\" style=\"color: #4c5763; line-height: 140%; text-align: center; word-wrap: break-word;\">\r\n"
				+ "                                <p style=\"margin: 0; font-size: 14px; line-height: 140%;\"><span style=\"font-size: 12px; line-height: 16.8px;\">Help people connect and learn</span>\r\n"
				+ "                                </p>\r\n"
				+ "                              </div>\r\n"
				+ "\r\n"
				+ "                            </td>\r\n"
				+ "                          </tr>\r\n"
				+ "                        </tbody>\r\n"
				+ "                      </table>\r\n"
				+ "\r\n"
				+ "                      <table style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; font-family: arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\" valign=\"top\">\r\n"
				+ "                        <tbody style=\"line-height: inherit;\">\r\n"
				+ "                          <tr style=\"line-height: inherit; vertical-align: top; border-collapse: collapse;\" valign=\"top\">\r\n"
				+ "                            <td style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; overflow-wrap: break-word; word-break: break-word; padding: 10px 20px 10px 10px; font-family: arial,helvetica,sans-serif;\" align=\"left\" valign=\"top\">\r\n"
				+ "\r\n"
				+ "                              <div align=\"center\" style=\"line-height: inherit;\">\r\n"
				+ "                                <div style=\"line-height: inherit; display: table; max-width: 140px;\">\r\n"
				+ "                                  <!--[if (mso)|(IE)]><table width=\"140\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"border-collapse:collapse;\" align=\"center\"><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"border-collapse:collapse; mso-table-lspace: 0pt;mso-table-rspace: 0pt; width:140px;\"><tr><![endif]-->\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "                                  <!--[if (mso)|(IE)]><td width=\"32\" style=\"width:32px; padding-right: 15px;\" valign=\"top\"><![endif]-->\r\n"
				+ "                                  <table align=\"left\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"32\" height=\"32\" style=\"line-height: inherit; color: #000000; display: inline-block; border-collapse: collapse; table-layout: fixed; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; vertical-align: top; margin-right: 15px; width: 32px; height: 32px;\" valign=\"top\">\r\n"
				+ "                                    <tbody style=\"line-height: inherit;\">\r\n"
				+ "                                      <tr style=\"line-height: inherit; border-collapse: collapse; vertical-align: top;\" valign=\"top\">\r\n"
				+ "                                        <td align=\"left\" valign=\"top\" style=\"line-height: inherit; color: #000000; word-break: break-word; vertical-align: top; border-collapse: collapse;\">\r\n"
				+ "                                          <a href=\"https://facebook.com/\" title=\"Facebook\" target=\"_blank\" style=\"line-height: inherit; color: #0000ee; text-decoration: underline;\">\r\n"
				+ "                                            <img src=\"https://i.ibb.co/09h8pR1/image-1.png\" alt=\"Facebook\" title=\"Facebook\" width=\"32\" style=\"line-height: inherit; outline: none; text-decoration: none; -ms-interpolation-mode: bicubic; clear: both; border: none; height: auto; float: none; display: block; max-width: 32px;\">\r\n"
				+ "                                          </a>\r\n"
				+ "                                        </td>\r\n"
				+ "                                      </tr>\r\n"
				+ "                                    </tbody>\r\n"
				+ "                                  </table>\r\n"
				+ "                                  <!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "\r\n"
				+ "                                  <!--[if (mso)|(IE)]><td width=\"32\" style=\"width:32px; padding-right: 15px;\" valign=\"top\"><![endif]-->\r\n"
				+ "                                  <table align=\"left\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"32\" height=\"32\" style=\"line-height: inherit; color: #000000; display: inline-block; border-collapse: collapse; table-layout: fixed; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; vertical-align: top; margin-right: 15px; width: 32px; height: 32px;\" valign=\"top\">\r\n"
				+ "                                    <tbody style=\"line-height: inherit;\">\r\n"
				+ "                                      <tr style=\"line-height: inherit; border-collapse: collapse; vertical-align: top;\" valign=\"top\">\r\n"
				+ "                                        <td align=\"left\" valign=\"top\" style=\"line-height: inherit; color: #000000; word-break: break-word; vertical-align: top; border-collapse: collapse;\">\r\n"
				+ "                                          <a href=\"https://twitter.com/\" title=\"Twitter\" target=\"_blank\" style=\"line-height: inherit; color: #0000ee; text-decoration: underline;\">\r\n"
				+ "                                            <img src=\"https://i.ibb.co/X7bg5QB/image-3.png\" alt=\"Twitter\" title=\"Twitter\" width=\"32\" style=\"line-height: inherit; outline: none; text-decoration: none; -ms-interpolation-mode: bicubic; clear: both; border: none; height: auto; float: none; display: block; max-width: 32px;\">\r\n"
				+ "                                          </a>\r\n"
				+ "                                        </td>\r\n"
				+ "                                      </tr>\r\n"
				+ "                                    </tbody>\r\n"
				+ "                                  </table>\r\n"
				+ "                                  <!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "\r\n"
				+ "                                  <!--[if (mso)|(IE)]><td width=\"32\" style=\"width:32px; padding-right: 0px;\" valign=\"top\"><![endif]-->\r\n"
				+ "                                  <table align=\"left\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"32\" height=\"32\" style=\"line-height: inherit; color: #000000; display: inline-block; border-collapse: collapse; table-layout: fixed; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; vertical-align: top; margin-right: 0px; width: 32px; height: 32px;\" valign=\"top\">\r\n"
				+ "                                    <tbody style=\"line-height: inherit;\">\r\n"
				+ "                                      <tr style=\"line-height: inherit; border-collapse: collapse; vertical-align: top;\" valign=\"top\">\r\n"
				+ "                                        <td align=\"left\" valign=\"top\" style=\"line-height: inherit; color: #000000; word-break: break-word; vertical-align: top; border-collapse: collapse;\">\r\n"
				+ "                                          <a href=\"https://instagram.com/\" title=\"Instagram\" target=\"_blank\" style=\"line-height: inherit; color: #0000ee; text-decoration: underline;\">\r\n"
				+ "                                            <img src=\"https://i.ibb.co/wYkPcpy/image-2.png\" alt=\"Instagram\" title=\"Instagram\" width=\"32\" style=\"line-height: inherit; outline: none; text-decoration: none; -ms-interpolation-mode: bicubic; clear: both; border: none; height: auto; float: none; display: block; max-width: 32px;\">\r\n"
				+ "                                          </a>\r\n"
				+ "                                        </td>\r\n"
				+ "                                      </tr>\r\n"
				+ "                                    </tbody>\r\n"
				+ "                                  </table>\r\n"
				+ "                                  <!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "                                  <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
				+ "                                </div>\r\n"
				+ "                              </div>\r\n"
				+ "\r\n"
				+ "                            </td>\r\n"
				+ "                          </tr>\r\n"
				+ "                        </tbody>\r\n"
				+ "                      </table>\r\n"
				+ "\r\n"
				+ "                      <!--[if (!mso)&(!IE)]><!-->\r\n"
				+ "                    </div>\r\n"
				+ "                    <!--<![endif]-->\r\n"
				+ "                  </div>\r\n"
				+ "                </div>\r\n"
				+ "                <!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "                <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
				+ "              </div>\r\n"
				+ "            </div>\r\n"
				+ "          </div>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "          <div class=\"u-row-container\" style=\"line-height: inherit; padding: 0px; background-color: transparent;\">\r\n"
				+ "            <div class=\"u-row\" style=\"line-height: inherit; Margin: 0 auto; min-width: 320px; max-width: 600px; overflow-wrap: break-word; word-wrap: break-word; word-break: break-word; background-color: #d9f7ed;\">\r\n"
				+ "              <div style=\"line-height: inherit; border-collapse: collapse; display: table; width: 100%; height: 100%; background-color: transparent;\">\r\n"
				+ "                <!--[if (mso)|(IE)]><table width=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\"><tr><td style=\"padding: 0px;background-color: transparent;\" align=\"center\"><table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:600px;\"><tr style=\"background-color: #d9f7ed;\"><![endif]-->\r\n"
				+ "\r\n"
				+ "                <!--[if (mso)|(IE)]><td align=\"center\" width=\"600\" style=\"width: 600px;padding: 0px;border-top: 0px solid transparent;border-left: 0px solid transparent;border-right: 0px solid transparent;border-bottom: 0px solid transparent;\" valign=\"top\"><![endif]-->\r\n"
				+ "                <div class=\"u-col u-col-100\" style=\"line-height: inherit; max-width: 320px; min-width: 600px; display: table-cell; vertical-align: top;\">\r\n"
				+ "                  <div style=\"line-height: inherit; height: 100%; width: 100%;\">\r\n"
				+ "                    <!--[if (!mso)&(!IE)]><!-->\r\n"
				+ "                    <div style=\"line-height: inherit; box-sizing: border-box; height: 100%; padding: 0px; border-top: 0px solid transparent; border-left: 0px solid transparent; border-right: 0px solid transparent; border-bottom: 0px solid transparent;\">\r\n"
				+ "                      <!--<![endif]-->\r\n"
				+ "\r\n"
				+ "                      <table style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; font-family: arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\" valign=\"top\">\r\n"
				+ "                        <tbody style=\"line-height: inherit;\">\r\n"
				+ "                          <tr style=\"line-height: inherit; vertical-align: top; border-collapse: collapse;\" valign=\"top\">\r\n"
				+ "                            <td style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; overflow-wrap: break-word; word-break: break-word; padding: 10px; font-family: arial,helvetica,sans-serif;\" align=\"left\" valign=\"top\">\r\n"
				+ "\r\n"
				+ "                              <table height=\"0px\" align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"line-height: inherit; color: #000000; border-collapse: collapse; table-layout: fixed; border-spacing: 0; mso-table-lspace: 0pt; mso-table-rspace: 0pt; vertical-align: top; border-top: 0px solid #d9f7ed; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%;\" valign=\"top\">\r\n"
				+ "                                <tbody style=\"line-height: inherit;\">\r\n"
				+ "                                  <tr style=\"line-height: inherit; border-collapse: collapse; vertical-align: top;\" valign=\"top\">\r\n"
				+ "                                    <td style=\"color: #000000; word-break: break-word; vertical-align: top; font-size: 0px; line-height: 0px; mso-line-height-rule: exactly; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; border-collapse: collapse;\" valign=\"top\">\r\n"
				+ "                                      <span style=\"line-height: inherit;\">&#160;</span>\r\n"
				+ "                                    </td>\r\n"
				+ "                                  </tr>\r\n"
				+ "                                </tbody>\r\n"
				+ "                              </table>\r\n"
				+ "\r\n"
				+ "                            </td>\r\n"
				+ "                          </tr>\r\n"
				+ "                        </tbody>\r\n"
				+ "                      </table>\r\n"
				+ "\r\n"
				+ "                      <table style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; font-family: arial,helvetica,sans-serif;\" role=\"presentation\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" border=\"0\" valign=\"top\">\r\n"
				+ "                        <tbody style=\"line-height: inherit;\">\r\n"
				+ "                          <tr style=\"line-height: inherit; vertical-align: top; border-collapse: collapse;\" valign=\"top\">\r\n"
				+ "                            <td style=\"line-height: inherit; vertical-align: top; border-collapse: collapse; color: #000000; overflow-wrap: break-word; word-break: break-word; padding: 10px; font-family: arial,helvetica,sans-serif;\" align=\"left\" valign=\"top\">\r\n"
				+ "\r\n"
				+ "                              <div class=\"v-text-align\" style=\"font-size: 13px; color: #7e8c8d; line-height: 140%; text-align: center; word-wrap: break-word;\">\r\n"
				+ "                                <p style=\"margin: 0; line-height: 140%;\">You received this email because we received a request for\r\n"
				+ "                                  register your account. If you didn't request an account, you can safely delete this\r\n"
				+ "                                  email.</p>\r\n"
				+ "                              </div>\r\n"
				+ "\r\n"
				+ "                            </td>\r\n"
				+ "                          </tr>\r\n"
				+ "                        </tbody>\r\n"
				+ "                      </table>\r\n"
				+ "\r\n"
				+ "                      <!--[if (!mso)&(!IE)]><!-->\r\n"
				+ "                    </div>\r\n"
				+ "                    <!--<![endif]-->\r\n"
				+ "                  </div>\r\n"
				+ "                </div>\r\n"
				+ "                <!--[if (mso)|(IE)]></td><![endif]-->\r\n"
				+ "                <!--[if (mso)|(IE)]></tr></table></td></tr></table><![endif]-->\r\n"
				+ "              </div>\r\n"
				+ "            </div>\r\n"
				+ "          </div>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "          <!--[if (mso)|(IE)]></td></tr></table><![endif]-->\r\n"
				+ "        </td>\r\n"
				+ "      </tr>\r\n"
				+ "    </tbody>\r\n"
				+ "  </table>\r\n"
				+ "  <!--[if mso]></div><![endif]-->\r\n"
				+ "  <!--[if IE]></div><![endif]-->\r\n"
				+ "</body>\r\n"
				+ "\r\n"
				+ "</html>";
		message.setContent(htmlContent, "text/html; charset=utf-8");
>>>>>>> refs/remotes/origin/main
		mailSender.send(message);
		
	}


}
